name: mindepsapi

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: vshakitskiy
      POSTGRES_DB: db
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
